import{createRemoteJWKSet,jwtVerify}from'jose';import{neon as postgres}from'@neondatabase/serverless';import{createUserStore,createRegistrar,validateNewUser,validateMember}from'./users.js';export class ApiError extends Error{constructor(status,message){super(message);this.status=status}}
async function readJson(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>10*1024*1024)throw new ApiError(413,'Dados muito grandes.');chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{throw new ApiError(400,'JSON inválido.')}}
export function createVerifier(url){const base=url.replace(/\/$/,''),origin=new URL(base).origin,keys=createRemoteJWKSet(new URL(`${base}/.well-known/jwks.json`));return async t=>(await jwtVerify(t,keys,{issuer:[origin,`${origin}/`,base],audience:origin,algorithms:['EdDSA','ES256','RS256'],requiredClaims:['sub','exp','iat']})).payload.sub}
export function validState(s){if(!s||typeof s!=='object'||!s.settings)throw new ApiError(400,'Estrutura inválida.');for(const k of['departments','employees','shifts','assignments']){if(!Array.isArray(s[k]))throw new ApiError(400,`Lista inválida: ${k}.`);const ids=new Set;for(const x of s[k]){if(!x?.id||ids.has(x.id))throw new ApiError(400,`Identificador inválido em ${k}.`);ids.add(x.id)}}return s}
const labels={departments:'setor',employees:'funcionário',shifts:'turno',assignments:'escala'};export function changes(before,next){const out=[];for(const key of Object.keys(labels)){const a=new Map((before[key]||[]).map(x=>[x.id,x])),b=new Map((next[key]||[]).map(x=>[x.id,x]));for(const[id,row]of b)out.push(!a.has(id)?{action:`Cadastrou ${labels[key]}`,entity:key,entityId:id,details:{name:row.name||row.title||row.date}}:JSON.stringify(a.get(id))!==JSON.stringify(row)?{action:`Alterou ${labels[key]}`,entity:key,entityId:id,details:{name:row.name||row.title||row.date}}:null);for(const[id,row]of a)if(!b.has(id))out.push({action:`Excluiu ${labels[key]}`,entity:key,entityId:id,details:{name:row.name||row.title||row.date}})}return out.filter(Boolean)}
function employeeView(state,email){const employee=(state.employees||[]).find(e=>e.email?.toLowerCase()===email?.toLowerCase());return{...state,departments:state.departments||[],employees:employee?[employee]:[],shifts:state.shifts||[],assignments:employee?(state.assignments||[]).filter(a=>a.employeeId===employee.id):[]}}
export function createStore(url){const sql=postgres(url);return{sql,async read(id){const r=await sql`select version,state from public.app_state where id=1 and exists(select 1 from public.app_members where user_id=${id})`;return r[0]?{version:Number(r[0].version),state:r[0].state}:null},async write(id,v,state){const r=await sql`update public.app_state set state=${JSON.stringify(state)}::jsonb,version=version+1 where id=1 and version=${v} and exists(select 1 from public.app_members where user_id=${id}) returning version,state`;return r[0]?{version:Number(r[0].version),state:r[0].state}:{conflict:true}},async log(actor,profile,entry,req){await sql`insert into public.audit_log(user_id,user_name,user_email,user_role,action,entity,entity_id,details,ip_address) values(${actor},${profile.name||''},${profile.email||''},${profile.role},${entry.action},${entry.entity||null},${entry.entityId||null},${JSON.stringify(entry.details||{})}::jsonb,${String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()})`},async logs(){return sql`select id,user_name "userName",user_email "userEmail",user_role "userRole",action,entity,entity_id "entityId",details,ip_address "ipAddress",created_at "createdAt" from public.audit_log order by created_at desc limit 1000`}}}
export function createApi({authUrl,databaseUrl}={}){const verify=authUrl?createVerifier(authUrl):null,db=databaseUrl?createStore(databaseUrl):null,members=db?createUserStore(db.sql):null,register=authUrl?createRegistrar(authUrl):null;return async(req,res,next=()=>{res.writeHead(404);res.end()})=>{const path=new URL(req.url,'http://local').pathname,send=(s,b)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(b))};if(!path.startsWith('/api/'))return next();if(path==='/api/health')return send(verify&&db?200:503,{configured:Boolean(verify&&db)});if(!verify||!db)return send(503,{message:'Configure Neon Auth e DATABASE_URL.'});try{
if(path==='/api/bootstrap'&&req.method==='POST'){if(await members.count())throw new ApiError(409,'Os acessos iniciais já foram criados.');const accounts=[{name:'Administrador Caxias em Escala',email:'admin@caxiasemescala.com.br',password:'CaxiasAdmin@2026',role:'Administrador'},{name:'Gestor de Escalas',email:'gestor@caxiasemescala.com.br',password:'CaxiasGestor@2026',role:'Gestor'}];for(const a of accounts){const id=await members.idByEmail(a.email)||await register(a,req.headers.origin);await members.authorizeFirst(id,a.role)}return send(201,{ok:true})}
const match=/^Bearer ([^\s]+)$/.exec(req.headers.authorization||'');if(!match)throw new ApiError(401,'Entre para acessar o sistema.');let id;try{id=await verify(match[1])}catch{throw new ApiError(401,'Sessão inválida ou expirada.')}const profile=await members.profile(id);if(!profile)throw new ApiError(403,'Acesso não autorizado.');
if(path==='/api/me'&&req.method==='GET'){await db.log(id,profile,{action:'Acessou o sistema'},req);return send(200,{id,...profile})}
if(path==='/api/audit'){if(req.method==='GET'){if(profile.role!=='Administrador')throw new ApiError(403,'Somente administradores consultam a auditoria.');return send(200,{logs:await db.logs()})}if(req.method==='POST'){const body=await readJson(req);await db.log(id,profile,{action:String(body.action||'Executou uma ação').slice(0,200)},req);return send(201,{ok:true})}}
if(path==='/api/users'){if(profile.role!=='Administrador')throw new ApiError(403,'Somente administradores gerenciam usuários.');if(req.method==='GET')return send(200,{users:await members.list(id)});const input=await readJson(req);if(req.method==='PUT'){const m=validateMember(input);await members.update(id,m);await db.log(id,profile,{action:`${m.active?'Autorizou/alterou':'Bloqueou'} usuário`,entity:'users',entityId:m.id,details:{role:m.role}},req);return send(200,{ok:true})}if(req.method==='POST'){const a=validateNewUser(input);const userId=await members.idByEmail(a.email)||await register(a,req.headers.origin);await members.update(id,{id:userId,role:a.role,active:true});await db.log(id,profile,{action:'Cadastrou usuário',entity:'users',entityId:userId,details:{email:a.email,role:a.role}},req);return send(201,{ok:true})}}
if(path==='/api/state'&&req.method==='GET'){const r=await db.read(id);if(!r)throw new ApiError(403,'Acesso não autorizado.');return send(200,profile.role==='Funcionário'?{...r,state:employeeView(r.state,profile.email)}:r)}
if(path==='/api/state'&&req.method==='PUT'){if(profile.role==='Funcionário')throw new ApiError(403,'Funcionários possuem acesso somente para consulta.');const body=await readJson(req);if(!Number.isSafeInteger(body.expected_version))throw new ApiError(400,'Versão inválida.');const before=await db.read(id),next=validState(body.next_state),r=await db.write(id,body.expected_version,next);if(!r.conflict){const list=changes(before.state,next);for(const entry of list.length?list:[{action:String(body.action||'Atualizou os dados')}])await db.log(id,profile,entry,req)}return send(200,r)}throw new ApiError(404,'Rota não encontrada.')
}catch(e){return send(e.status||500,{message:e instanceof ApiError?e.message:'Não foi possível acessar o banco de dados.'})}}}
